#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2014-11-29 01:02:47 +0000 (Sat, 29 Nov 2014)
#
#  https://github.com/harisekhon/nagios-plugins
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#  to help improve or steer this or other code I publish
#
#  http://www.linkedin.com/in/harisekhon
#

language: perl
perl:
  - "5.22"
  # this build has thread support
  - "5.18-shrplib"
  #- "5.16"
  # latest Redis cpan module requires Perl >= 5.10
  - "5.10"
  # there is workaround in build now to install older version if latest fails for RHEL5/CentOS5 servers
  # other CPAN modules are broken for Perl 5.8, re-visit
  #- "5.8"

sudo: required

notifications:
  email: false

branches:
  only:
    - master

install:
  #- pushd lib
  #- make apt-packages
  #- cpanm --installdeps --notest . || echo CPANM LIB FAILED
  #- popd
  #- make apt-packages
  #- cpanm --installdeps --notest . || echo CPANM FAILED
  # integrated cpanm in to core Makefiles
  # workaround for strange error when building pylib submodule, /usr/local/lib/python2.7, /usr/local/man, /usr/lib/python2.7 etc...
  # can't do /usr/lib, otherwise /usr/lib/sudo/sudoers.so breaks with "sudo: /usr/lib/sudo/sudoers.so must be only be writable by owner"
  # 777 causes "Insecure directory in $ENV{PATH} while running with -T switch at lib/HariSekhonUtils.pm line 1316" - nice catch to this hackery by Perl taint security
  #- sudo chmod -R 755 /opt/python /usr/local /usr/lib/python*
  # with 755 perms goes back to "error: could not create '/usr/local/lib/python2.7/dist-packages/markupsafe': Permission denied"
  # chown root still same error... must be because pure python submodules don't sudo in Travis
  - sudo chown -R travis /opt/python /usr/local /usr/lib/python*
  - make
  - make zookeeper

script:
  - tests/all.sh

services:
  # docker breaks cassandra, mysql, probably everything
  # => wholesale switch over to dockerized testing instead
  - docker
#  - cassandra
#  #- couchdb
#  - elasticsearch
#  - memcached
#  - mongodb
#  - mysql
#  #- postgreql
#  - neo4j
#  #- rabbitmq
#  - redis
#  - riak

# env stuff is handled with docker test scripts now
#env:
#  global:
#    - MYSQL_DATABASE=mysql
#    - MYSQL_PASSWORD=""
#    - MYSQL_USER=travis
